In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../Dataset/IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
def lowering(text):
    return text.lower()


df["review"]=df["review"].apply(lowering)

In [6]:
from bs4 import BeautifulSoup

def remove_html_tags(text):
    return BeautifulSoup(text, "html.parser").get_text()

df["review"]=df["review"].apply(remove_html_tags)

In [8]:
import string,time



def remove_punctuation(value):
    return value.translate(str.maketrans('','',string.punctuation))

df["review"]=df["review"].apply(remove_punctuation)

In [9]:
from nltk.corpus import stopwords

stop=stopwords.words("english")

In [10]:
def stopword_removal(text):
    ll=[]
    for word in text.split():
        if word not in stop:
            ll.append(word)
    return " ".join(ll)

In [11]:
df["review"]=df["review"].apply(stopword_removal)
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [12]:
from nltk import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

def lemma(text):
    ll=[]
    for word in text.split():
        ll.append(lemmatizer.lemmatize(word))
    return " ".join(ll)

In [13]:
df["review"]=df["review"].apply(lemma)

In [14]:
def convert_label(x):
    if(x=="positive"):
        return 1
    else:
        return 0
    
df["sentiment"]=df["sentiment"].apply(convert_label)

In [15]:
X=df["review"]
y=df["sentiment"]

In [19]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=.25)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer=TfidfVectorizer(max_features=10000)

In [21]:
transformed_train=vectorizer.fit_transform(x_train)

In [25]:
print(vectorizer.vocabulary_)

{'john': 4939, 'carpenter': 1445, 'greatest': 4024, 'horror': 4423, 'film': 3505, 'time': 9084, 'maybe': 5648, 'everyone': 3211, 'always': 440, 'sheer': 8033, 'genius': 3852, 'hold': 4364, 'special': 8381, 'place': 6677, 'heart': 4242, 'unfortunate': 9393, 'didnt': 2601, 'get': 3870, 'see': 7890, 'twenty': 9302, 'year': 9956, 'release': 7342, 'even': 3200, 'later': 5176, 'many': 5562, 'slasher': 8204, 'copy': 2087, 'cat': 1482, 'come': 1842, 'gone': 3945, 'still': 8558, 'gave': 3828, 'impact': 4559, 'must': 5991, 'done': 2767, 'father': 3427, 'suggested': 8717, 'go': 3928, 'halloween': 4139, 'whip': 9794, 'rent': 7399, 'full': 3762, 'story': 8585, 'watching': 9711, 'quite': 7109, 'clear': 1725, 'defined': 2431, 'set': 7967, 'plot': 6718, 'simple': 8137, '1963': 58, 'michael': 5754, 'audrey': 750, 'myers': 6001, 'killed': 5060, 'sister': 8165, 'judith': 4974, 'cold': 1808, 'blood': 1088, 'large': 5163, 'butcher': 1323, 'knife': 5090, 'fifteen': 3491, 'treated': 9230, 'dr': 2799, 'sam': 7735, 'escape': 3166, 'return': 7492, 'hometown': 4381, 'begin': 941, 'stalking': 8479, 'three': 9045, 'young': 9970, 'girl': 3894, 'laurie': 5194, 'innocent': 4687, 'annie': 509, 'tough': 9162, 'talking': 8880, 'sarcastic': 7760, 'van': 9504, 'der': 2518, 'beautiful': 918, 'sexually': 7987, 'track': 9175, 'help': 4274, 'town': 9169, 'sheriff': 8045, 'leigh': 5238, 'remains': 7367, 'skeptical': 8181, 'psychotic': 7035, 'killer': 5061, 'watch': 9707, 'killing': 5062, 'one': 6284, 'sweet': 8826, 'left': 5230, 'prime': 6919, 'target': 8892, 'casting': 1476, 'brilliant': 1232, 'actor': 251, 'actress': 253, 'top': 9141, 'notch': 6168, 'performance': 6571, 'jamie': 4881, 'lee': 5229, 'curtis': 2278, 'stunning': 8652, 'first': 3548, 'role': 7618, 'donald': 2766, 'pleasance': 6706, 'thrilling': 9051, 'small': 8246, 'nick': 6107, 'castle': 1477, 'portrays': 6794, 'outstanding': 6374, 'job': 4932, 'soulless': 8348, 'evil': 3218, 'walk': 9657, 'body': 1111, 'movement': 5948, 'great': 4022, 'highlight': 4317, 'chilling': 1623, 'score': 7828, 'created': 2182, 'recognizable': 7254, 'theme': 8998, 'known': 5100, 'today': 9109, 'blue': 1098, 'lighting': 5295, 'creepy': 2198, 'effective': 2970, 'moment': 5882, 'wall': 9662, 'seeing': 7893, 'dead': 2374, 'friend': 3736, 'shadow': 7996, 'behind': 951, 'face': 3347, 'strike': 8617, 'mask': 5613, 'thing': 9020, 'sent': 7937, 'chill': 1621, 'spine': 8410, 'white': 9797, 'emotionless': 3051, 'worked': 9894, 'make': 5521, 'gory': 3965, 'unlike': 9419, 'cheesy': 1598, 'friday': 3734, '13th': 12, 'fact': 3353, 'little': 5345, 'work': 9893, 'instead': 4719, 'suspense': 8802, 'tension': 8957, 'became': 922, 'spawned': 8375, 'movie': 5949, 'like': 5300, 'character': 1557, 'jason': 4893, 'mere': 5726, 'rip': 7567, 'sum': 8731, 'suggest': 8716, 'least': 5222, 'life': 5282, 'landmark': 5153, 'making': 5524, 'without': 9866, 'doubt': 2784, 'fun': 3766, 'ive': 4864, 'cinema': 1681, 'long': 5386, 'however': 4440, 'able': 170, 'say': 7784, 'whether': 9788, 'good': 3947, 'bad': 821, 'simply': 8142, 'cannot': 1388, 'applied': 579, 'picture': 6645, 'everything': 3213, 'could': 2119, 'ever': 3205, 'characteristic': 1559, 'romantic': 7628, 'comedy': 1846, 'political': 6757, 'commentary': 1860, 'thriller': 9050, 'drama': 2809, 'action': 245, 'musical': 5988, 'selfconscious': 7912, 'art': 649, 'adding': 269, 'basic': 878, 'premise': 6876, 'indian': 4630, 'couple': 2135, 'kapoor': 5006, 'happily': 4171, 'living': 5352, 'canada': 1375, 'rush': 7695, 'india': 4629, 'visit': 9606, 'husband': 4479, 'parent': 6469, 'disturbing': 2725, 'news': 6099, 'report': 7417, 'rest': 7467, 'take': 8869, 'find': 3529, 'midst': 5768, 'violence': 9590, 'point': 6737, 'borrows': 1153, 'baby': 804, 'call': 1353, 'remake': 7368, 'anything': 549, 'would': 9911, 'line': 5316, 'number': 6196, 'astonishing': 705, 'including': 4608, 'shah': 8001, 'rukh': 7680, 'khan': 5043, 'dream': 2821, 'another': 523, 'two': 9309, 'star': 8494, 'poster': 6814, 'appear': 570, 'really': 7228, 'late': 5173, 'end': 3073, 'real': 7214, 'yet': 9965, 'spirited': 8415, 'truly': 9272, 'unexpected': 9381, 'admirable': 279, 'link': 5321, 'twist': 9306, 'turn': 9294, 'show': 8088, 'believable': 958, 'emotion': 3048, 'notable': 6166, 'presence': 6883, 'nana': 6021, 'play': 6698, 'every': 3207, 'scene': 7805, 'he': 4227, 'scary': 7802, 'nuanced': 6191, 'share': 8018, 'realism': 7218, 'rampant': 7153, 'abuse': 191, 'received': 7243, 'female': 3464, 'getting': 3871, 'beaten': 913, 'occasion': 6228, 'clearly': 1727, 'ultimately': 9323, 'becomes': 927, 'surreal': 8783, 'dramatic': 2810, 'sequence': 7949, 'usually': 9481, 'followed': 3626, 'comic': 1850, 'spectacular': 8388, 'overall': 6382, 'effect': 2969, 'nothing': 6172, 'seen': 7901, 'bollywood': 1119, 'mixing': 5854, 'genre': 3853, 'incredible': 4624, 'resolution': 7452, 'certainly': 1527, 'norm': 6151, 'raise': 7141, 'bar': 850, 'absorbing': 186, 'greater': 4023, 'becoming': 928, 'ridiculous': 7553, 'achieves': 232, 'grandeur': 3997, 'tragedy': 9183, 'audience': 747, 'equally': 3151, 'entertained': 3124, 'pure': 7062, 'gratuitous': 4015, 'director': 2637, 'throwing': 9058, 'trick': 9247, 'book': 1135, 'perhaps': 6576, 'message': 5735, 'inspiring': 4714, 'extent': 3328, 'love': 5422, 'thought': 9035, 'mind': 5790, 'came': 1359, 'world': 9897, 'opening': 6298, 'eye': 3338, 'patch': 6505, 'wearing': 9732, 'named': 6018, 'smooth': 8263, 'forehead': 3649, 'follows': 3629, 'johnny': 4940, 'shown': 8096, 'scar': 7791, 'thats': 8990, 'continuity': 2033, 'lapse': 5161, 'edgy': 2953, 'spaghetti': 8365, 'western': 9773, 'rather': 7187, 'detract': 2568, 'add': 264, 'flavor': 3576, 'occurs': 6238, 'examined': 3233, 'identity': 4507, 'cant': 1389, 'imagine': 4542, 'false': 3382, 'immediately': 4553, 'carradine': 1447, 'lawrence': 5199, 'collect': 1817, 'bounty': 1168, 'wanted': 9677, 'principal': 6923, 'mark': 5582, 'damon': 2318, 'alternately': 433, 'right': 7559, 'hip': 4334, 'throughout': 9054, 'gun': 4100, 'belt': 970, 'following': 3628, 'brawl': 1202, 'bound': 1166, 'san': 7742, 'uncle': 9340, 'request': 7432, 'avenge': 771, 'death': 2385, 'hand': 4150, 'wife': 9819, 'samantha': 7736, 'conniving': 1976, 'brother': 1255, 'louis': 5417, 'ride': 7550, 'best': 991, 'music': 5987, 'record': 7262, 'saloon': 7731, 'fight': 3494, 'got': 3970, 'kick': 5044, 'kung': 5117, 'fu': 3754, 'sound': 8349, 'punch': 7050, 'exaggeration': 3230, 'duel': 2874, 'wipe': 9850, 'amount': 468, 'lip': 5327, 'manages': 5538, 'entire': 3135, 'similarly': 8134, 'smack': 8245, 'around': 634, 'doesnt': 2751, 'cut': 2285, 'arrives': 644, 'covered': 2147, 'probably': 6936, 'clint': 1749, 'eastwood': 2931, 'reasonably': 7233, 'suitable': 8725, 'stand': 8485, 'exterior': 3329, 'seemed': 7897, 'replacement': 7413, 'obligatory': 6208, 'total': 9157, 'guy': 4110, 'exchange': 3247, 'seem': 7896, 'sense': 7930, 'tied': 9073, 'together': 9112, 'ended': 3076, 'knew': 5089, 'henchman': 4280, 'wind': 9841, 'due': 2873, 'part': 6479, 'case': 1464, 'youre': 9974, 'wondering': 9883, 'title': 9105, 'hero': 4292, 'adam': 258, 'classic': 1710, 'tv': 9299, 'rebel': 7237, 'name': 6017, 'gunfight': 4102, 'unique': 9407, 'element': 3002, 'way': 9719, 'pulled': 7045, 'string': 8620, 'shooting': 8070, 'beat': 912, 'retreat': 7488, 'revenge': 7504, 'alive': 399, 'look': 5391, 'try': 9280, 'shoot': 8068, 'miss': 5834, 'water': 9712, 'aimed': 357, 'desperately': 2547, 'difficult': 2613, 'subject': 8668, 'pull': 7044, 'convincingly': 2073, 'passion': 6499, 'involved': 4810, 'generally': 3844, 'pale': 6443, 'imitation': 4550, 'worse': 9904, 'slightly': 8225, 'avoid': 776, 'delivers': 2460, 'moving': 5959, 'sexy': 7988, 'thoroughly': 9033, 'engrossing': 3098, 'tale': 8873, 'disaster': 2658, 'possible': 6809, 'redemption': 7279, 'touching': 9161, 'deeper': 2418, 'human': 4455, 'core': 2091, 'mathieu': 5634, '18': 18, 'solitary': 8304, 'boy': 1178, 'meet': 5688, 'lonely': 5383, 'holiday': 4368, 'family': 3387, 'summer': 8735, 'fall': 3378, 'decide': 2400, 'live': 5348, 'relationship': 7336, 'catastrophe': 1483, 'cheat': 1585, 'distraught': 2718, 'survives': 8794, 'order': 6324, 'perspective': 6592, 'back': 810, 'seaside': 7869, 'met': 5740, 'told': 9116, 'never': 6091, 'much': 5963, 'implied': 4566, 'happens': 4169, 'intricate': 4779, 'narrative': 6029, 'essential': 3173, 'feeling': 3457, 'experienced': 3288, 'use': 9473, 'counterpoint': 2128, 'fortunately': 3678, 'timeline': 9088, 'used': 9474, 'psychiatric': 7026, 'hospital': 4425, 'winter': 9849, 'colour': 1830, 'warm': 9686, 'yellow': 9961, 'orange': 6319, 'almost': 421, 'warming': 9687, 'brown': 1258, 'main': 5511, 'put': 7076, 'excellent': 3238, 'though': 9034, 'whilst': 9789, 'delight': 2450, 'capacity': 1395, 'im': 4535, 'limp': 5312, 'mention': 5717, 'feel': 3455, 'loneliness': 5382, 'beautifully': 919, 'crafted': 2163, 'gesture': 3869, 'across': 241, 'far': 3396, 'dialogue': 2590, 'touched': 9160, 'upon': 9460, 'french': 3726, 'difficulty': 2614, 'understanding': 9365, 'fully': 3765, 'shifting': 8052, 'sand': 7743, 'meaning': 5666, 'indeed': 4626, 'key': 5041, 'trying': 9281, 'understand': 9362, 'attempted': 728, 'kill': 5059, 'psychiatrist': 7027, 'asks': 675, 'cheated': 1586, 'non': 6139, 'well': 9755, 'yes': 9963, 'brought': 1257, 'suicide': 8723, 'attempt': 727, 'none': 6140, 'contact': 2012, 'leaf': 5211, 'lost': 5412, 'forever': 3654, 'something': 8316, 'meaningless': 5668, 'affair': 317, 'darker': 2344, 'pierre': 6651, 'et': 3183, 'hope': 4403, 'slow': 8233, 'painful': 6431, 'touch': 9159, 'local': 5360, 'finally': 3524, 'may': 5647, 'next': 6101, 'teenage': 8930, 'within': 9865, 'beginning': 942, 'tell': 8935, 'talented': 8875, 'shell': 8037, 'day': 2367, 'etc': 3184, 'think': 9021, 'theyre': 9015, 'nice': 6102, 'directed': 2633, 'talent': 8874, 'jane': 4883, 'apart': 554, 'overrated': 6394, 'common': 1871, 'direct': 2632, 'woman': 9877, 'australian': 758, 'give': 3896, 'deemed': 2416, 'swallow': 8811, 'hard': 4175, 'accept': 199, 'ill': 4525, 'shes': 8049, 'cute': 2286, 'fascinating': 3410, 'lack': 5132, 'lie': 5280, 'dealing': 2380, 'people': 6560, 'crew': 2199, 'notice': 6173, 'easier': 2926, 'wander': 9670, 'unconvincing': 9346, 'depiction': 2511, 'filmed': 3508, 'wrong': 9936, 'half': 4134, 'wonder': 9879, 'completed': 1904, 'fictional': 3483, 'task': 8897, 'creating': 2184, 'brand': 1192, 'new': 6094, '1980s': 77, 'flick': 3589, 'fat': 3422, 'chance': 1545, 'suspect': 8798, 'actual': 254, 'realised': 7216, 'couldnt': 2120, 'settled': 7972, 'sigh': 8117, 'knowing': 5098, 'parody': 6476, 'course': 2139, 'enough': 3112, 'soon': 8327, 'cast': 1474, 'foot': 3638, 'isolated': 4840, 'mansion': 5559, 'spends': 8400, 'badly': 824, 'less': 5256, 'open': 6296, '80': 154, 'starring': 8502, 'true': 9271, 'molly': 5880, 'better': 999, 'sign': 8119, 'wishing': 9860, '1990s': 88, 'drop': 2847, 'stuff': 8645, 'mean': 5663, 'id': 4498, 'wondered': 9880, 'teen': 8929, 'accent': 198, 'know': 5097, 'strangely': 8598, 'glad': 3899, 'need': 6063, 'fulfilled': 3760, 'huge': 4447, 'freddy': 3718, 'krueger': 5112, 'dont': 2771, 'robert': 7597, 'englund': 3097, 'nightmare': 6119, 'elm': 3022, 'street': 8607, 'offense': 6252, 'acting': 244, 'worth': 9907, 'sequel': 7948, 'isnt': 4839, 'moviesthe': 5956, 'original': 6335, 'goodthe': 3955, '2nd': 124, 'opinion': 6306, '3rd': 133, 'okay': 6269, 'havent': 4216, 'mistake': 5842, 'piece': 6649, 'crap': 2166, 'watched': 9709, '25': 119, 'interesting': 4755, 'saw': 7783, 'definitely': 2435, 'martin': 5601, 'sheen': 8031, 'billing': 1026, 'lesser': 5257, 'marlon': 5587, 'brando': 1193, 'appears': 574, 'last': 5169, '30': 125, 'minute': 5811, 'hour': 4433, '17': 17, 'theatrical': 8995, 'version': 9547, 'unfair': 9384, 'fantastic': 3393, 'especially': 3169, 'narration': 6028, 'run': 7686, 'heard': 4239, 'voice': 9620, 'haunting': 4215, 'relates': 7333, 'adventure': 304, 'fail': 3360, 'appreciate': 582, 'moviethe': 5957, 'memorable': 5707, 'forgotten': 3664, 'losing': 5410, 'hotel': 4431, 'room': 7637, 'duvall': 2899, 'totally': 9158, 'surfing': 8775, 'ensuing': 3116, 'attack': 723, 'wagner': 9647, 'classical': 1711, 'helicopter': 4268, 'playboy': 6699, 'bunny': 1296, 'entertaining': 3126, 'troop': 9264, 'forrest': 3674, 'freaked': 3713, 'tiger': 9076, 'close': 1757, 'jungle': 4990, 'weird': 9749, 'appearance': 571, 'hippie': 4336, 'journalist': 4961, 'dennis': 2492, 'hopper': 4411, 'greeting': 4034, 'bizarre': 1049, 'strange': 8597, 'enjoyed': 3105, 'unpleasant': 9430, 'anymore': 546, 'slaughtered': 8207, 'boat': 1108, 'goofy': 3958, 'profanity': 6951, 'led': 5227, 'lot': 5413, 'anyone': 547, 'sure': 8770, 'remember': 7373, 'bloke': 1085, 'welch': 9752, 'finest': 3533, 'cardboard': 1417, 'cutout': 2287, 'act': 242, 'showing': 8095, 'considerable': 1989, 'asset': 684, 'surprising': 8781, 'big': 1012, 'fan': 3389, 'harry': 4197, 'convincing': 2072, 'bill': 1023, 'de': 2373, 'enjoy': 3103, 'sleeping': 8215, 'edward': 2967, 'assume': 695, 'mess': 5734, 'nonexistent': 6142, 'unfunny': 9395, 'script': 7851, 'puerile': 7041, 'slapstick': 8202, 'annoying': 518, '60': 146, 'caper': 1397, 'werent': 9768, 'given': 3897, 'said': 7722, 'treat': 9229, 'delicious': 2448, 'cameo': 1360, 'reason': 7231, 'alone': 422, 'reluctant': 7358, 'hired': 4339, 'king': 5070, 'dragon': 2806, 'oh': 6265, 'entirely': 3136, 'composed': 1912, 'island': 4838, 'floating': 3598, 'cloud': 1769, 'dangerous': 2329, 'leap': 5215, 'journey': 4962, 'flow': 3605, 'city': 1692, 'horizon': 4413, 'stumbled': 8648, 'onto': 6294, 'accident': 207, 'pixar': 6675, 'computer': 1918, 'animated': 500, 'animator': 502, 'invested': 4799, 'screen': 7843, 'attention': 735, 'detail': 2562, 'staggering': 8468, 'green': 4031, 'smoke': 8261, 'background': 813, 'favourite': 3436, 'monster': 5897, 'also': 429, 'wonderful': 9881, 'charm': 1572, 'keep': 5024, 'protagonist': 7001, 'likable': 5299, 'impossible': 4573, 'quest': 7093, 'reach': 7202, 'destroy': 2555, 'might': 5770, 'otherwise': 6347, 'path': 6506, 'hector': 4258, 'creature': 2189, 'crazy': 2179, 'grin': 4048, 'tendency': 8951, 'speak': 8376, 'mixture': 5855, 'nonsense': 6144, 'english': 3096, 'provides': 7015, 'relief': 7352, 'jar': 4890, 'summary': 8733, 'recommend': 7258, 'hunter': 4473, 'opportunity': 6309, 'animation': 501, 'breathtaking': 1216, 'battle': 894, 'glimpse': 3912, 'else': 3025, 'youve': 9978, 'television': 8934, 'spend': 8398, 'matter': 5637, 'nine': 6122, 'follow': 3625, 'fleet': 3583, 'rko': 7586, 'production': 6949, '1936': 30, 'fred': 3716, 'astaire': 702, 'ginger': 3892, 'rogers': 7615, 'complex': 1906, 'although': 435, 'similar': 8132, 'helped': 4275, 'create': 2181, 'worthwhile': 9909, 'storyline': 8586, 'relevant': 7349, 'situation': 8171, 'society': 8292, 'made': 5488, 'relies': 7353, 'heavily': 4254, 'layered': 5203, 'satisfying': 7773, 'general': 3843, 'revolves': 7522, 'baker': 830, 'sailor': 7724, 'navy': 6049, 'played': 6700, 'sherry': 8048, 'former': 3669, 'dance': 2322, 'partner': 6488, 'singer': 8152, 'dancer': 2324, 'ship': 8056, 'smith': 8259, 'photo': 6625, 'reveals': 7501, 'asked': 673, 'marry': 5594, 'suggests': 8721, 'land': 5149, 'major': 5519, 'second': 7876, 'connie': 1975, 'refused': 7308, 'entry': 3141, 'paradise': 6461, 'unless': 9417, 'gentleman': 3855, 'bag': 828, 'waiting': 9653, 'buy': 1329, 'entrance': 3140, 'depressed': 2513, 'luck': 5445, 'men': 5709, 'performing': 6574, 'stage': 8465, 'enters': 3122, 'approach': 586, 'sight': 8118, 'remainder': 7364, 'rising': 7574, 'comedic': 1845, 'trouble': 9267, 'several': 7978, 'mini': 5797, 'falling': 3380, 'hit': 4348, 'compete': 1890, 'competition': 1894, 'winning': 9847, 'reminding': 7380, 'success': 8696, 'pleasure': 6712, 'pleasing': 6711, 'house': 4434, 'series': 7955, 'happy': 4173, 'event': 3202, 'unsettling': 9441, 'measure': 5673, 'brings': 1236, 'previous': 6909, 'night': 6116, 'midnight': 5767, 'morning': 5921, 'unfortunately': 9394, 'returned': 7493, 'upsetting': 9464, 'leaving': 5225, 'typical': 9314, 'looking': 5394, 'mood': 5907, 'changed': 1550, 'subplot': 8675, 'entered': 3119, 'party': 6490, 'shot': 8079, 'taking': 8871, 'tour': 9163, 'alternate': 432, 'build': 1282, 'confidence': 1947, 'intention': 4748, 'interrupted': 4767, 'oblivious': 6210, 'playing': 6703, 'coming': 1852, 'companion': 1878, 'missed': 5835, 'sounding': 8351, 'deck': 2406, 'company': 1879, 'lady': 5139, 'intrigued': 4781, 'ask': 672, 'hear': 4238, 'gladly': 3901, 'entertain': 3123, 'dancing': 2325, 'bring': 1234, 'happiness': 4172, 'returning': 7494, 'intertwined': 4769, 'prove': 7010, 'landing': 5151, 'unaware': 9333, 'word': 9891, 'studio': 8642, 'remarkable': 7371, 'unable': 9329, 'sing': 8151, 'correctly': 2103, 'destroying': 2557, 'audition': 749, 'addition': 270, 'spent': 8401, 'money': 5887, 'repair': 7403, 'hoping': 4409, 'captain': 1407, 'planned': 6688, 'dinner': 2629, 'date': 2357, 'supposed': 8766, 'aware': 786, 'marrying': 5595, 'longer': 5387, 'interested': 4754, 'stood': 8577, 'continues': 2031, 'format': 3667, 'climactic': 1742, 'reached': 7203, 'ending': 3077, 'interest': 4753, 'deal': 2378, 'pain': 6430, 'struggle': 8632, 'relate': 7331, 'incorporate': 4617, 'unrelated': 9436, 'subplots': 8676, 'carry': 1455, 'countless': 2130, 'romance': 7625, 'song': 8324, 'successfully': 8698, 'technique': 8922, 'aid': 354, 'saddest': 7713, 'cared': 1420, 'leave': 5224, 'review': 7508, 'noone': 6148, 'felt': 3463, 'comment': 1859, 'tom': 9121, 'hank': 4162, 'award': 784, 'humanity': 4456, 'tenderness': 8953, 'beauty': 920, 'gay': 3829, 'printed': 6926, 'text': 8979, 'suffice': 8713, 'want': 9676, '70': 149, 'modern': 5872, 'drug': 2853, 'cocktail': 1792, 'allowed': 411, 'breathe': 1213, 'personal': 6588, 'despite': 2551, 'actually': 255, 'silver': 8130, 'arrived': 643, 'called': 1354, 'cancer': 1380, 'government': 3976, 'preferred': 6865, 'let': 5261, 'die': 2602, 'red': 7275, 'cent': 1518, 'research': 7441, 'save': 7778, 'bunch': 1295, 'heterosexual': 4302, 'disease': 2678, 'wasnt': 9702, 'ready': 7212, 'straight': 8590, 'began': 938, 'organization': 6329, 'association': 692, 'available': 770, 'example': 3234, 'project': 6968, 'died': 2603, 'result': 7477, 'ordinary': 6326, 'suddenly': 8707, 'found': 3686, 'counting': 2129, 'needing': 6065, 'existed': 3267, 'broke': 1245, 'barrier': 866, 'prejudice': 6870, 'equal': 3150, 'harder': 4179, 'become': 926, 'nevertheless': 6092, 'stride': 8616, 'write': 9930, 'country': 2131, 'marriage': 5591, 'gain': 3792, 'taken': 8870, 'sad': 7712, 'obvious': 6226, 'writing': 9934, 'bit': 1041, 'comfort': 1848, 'realizing': 7226, 'vain': 9494, 'girlfriend': 3895, 'cheaply': 1584, 'scripted': 7852, 'read': 7208, 'different': 2611, 'author': 762, 'listened': 5334, 'audio': 748, 'seriously': 7957, 'lacking': 5134, 'contained': 2014, 'experience': 3287, 'blair': 1056, 'witch': 9862, 'vulgar': 9640, 'using': 9478, 'bed': 929, 'pan': 6451, 'content': 2022, 'throw': 9055, 'whole': 9801, 'laugh': 5182, 'nasty': 6035, 'someone': 8315, 'bell': 963, 'dress': 2828, 'step': 8535, 'front': 3744, 'mother': 5933, 'leading': 5210, 'sick': 8108, 'waste': 9703, 'begs': 943, 'toilet': 9113, 'paper': 6457, 'sickening': 8109, 'joy': 4963, 'makeup': 5523, 'reverend': 7505, 'james': 4880, 'older': 6272, 'man': 5533, 'fish': 3553, 'joshua': 4958, 'ladder': 5137, 'tried': 9249, 'serious': 7956, 'bathroom': 891, 'problem': 6937, 'inexperienced': 4648, 'downfall': 2791, 'commercial': 1864, 'station': 8515, 'product': 6948, 'chose': 1652, 'produce': 6944, 'correct': 2102, 'manner': 5554, 'rate': 7184, 'capital': 1398, 'minus': 5810, 'entertainment': 3127, 'benny': 979, 'took': 9136, 'eddie': 2948, 'reminded': 7378, 'sandra': 7746, 'bullock': 1289, 'sharp': 8023, 'nail': 6013, 'mine': 5794, 'growing': 4071, 'brooklyn': 1251, 'loved': 5423, 'pot': 6817, 'cook': 2075, 'lol': 5376, 'learned': 5218, 'hundred': 4465, 'loyal': 5438, 'reader': 7209, 'imdb': 4545, 'posted': 6813, 'middle': 5762, 'road': 7588, 'either': 2989, 'hate': 4207, 'ap

In [28]:
print(vectorizer.get_feature_names_out())

['007' '010' '10' ... 'zoom' 'zorro' 'zucco']

In [29]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()

In [30]:
model.fit(transformed_train,y_train)

MultinomialNB()

In [31]:
transformed_test=vectorizer.transform(x_test)

In [32]:
pred=model.predict(transformed_test)

In [33]:
from sklearn.metrics import classification_report

print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       0.85      0.86      0.86      6256
           1       0.86      0.85      0.86      6244

    accuracy                           0.86     12500
   macro avg       0.86      0.86      0.86     12500
weighted avg       0.86      0.86      0.86     12500